export const MenuUrlRoute = "/menus"
export const SlideUrlRoute = "/slider"
export const UslugiUrlRoute = "/uslugi"
export const NewsUrlRoute = "/news"
export const PortUrlRoute = "/portfolio"
export const AboutUrlRoute = "/about"
export const ServisesUrlRoute = "/services"